/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesSignalProcessingFourier1dRouteImport } from './routes/modules.signal-processing.fourier-1d'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesSignalProcessingFourier1dRoute =
  ModulesSignalProcessingFourier1dRouteImport.update({
    id: '/modules/signal-processing/fourier-1d',
    path: '/modules/signal-processing/fourier-1d',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modules/signal-processing/fourier-1d': typeof ModulesSignalProcessingFourier1dRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modules/signal-processing/fourier-1d': typeof ModulesSignalProcessingFourier1dRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modules/signal-processing/fourier-1d': typeof ModulesSignalProcessingFourier1dRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modules/signal-processing/fourier-1d'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modules/signal-processing/fourier-1d'
  id: '__root__' | '/' | '/modules/signal-processing/fourier-1d'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulesSignalProcessingFourier1dRoute: typeof ModulesSignalProcessingFourier1dRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/signal-processing/fourier-1d': {
      id: '/modules/signal-processing/fourier-1d'
      path: '/modules/signal-processing/fourier-1d'
      fullPath: '/modules/signal-processing/fourier-1d'
      preLoaderRoute: typeof ModulesSignalProcessingFourier1dRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulesSignalProcessingFourier1dRoute: ModulesSignalProcessingFourier1dRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
