import { useState } from 'react'
import { BookOpen, ChevronDown, ChevronUp, Sparkles, Compass } from 'lucide-react'
import { MathFormula } from '../../common/MathFormula'

export function WaveletPhaseTheoryDrawer() {
  const [isOpen, setIsOpen] = useState(true)

  return (
    <div className="card bg-base-100 border border-base-300 shadow-sm transition-all duration-200">
      <div
        className="card-body p-4 cursor-pointer select-none flex flex-row items-center justify-between"
        onClick={() => setIsOpen(!isOpen)}
      >
        <div className="flex items-center gap-3">
          <div className="p-2 bg-accent/10 text-accent rounded-lg">
            <BookOpen className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="font-bold text-base tracking-tight">
                Theory & Reference: Oz Yilmaz §1.1 (Phase Considerations)
              </h2>
              <span className="badge badge-accent badge-sm font-mono">Wavelet Phase</span>
            </div>
            <p className="text-xs text-base-content/70">
              Zero-phase vs. minimum-phase wavelets, energy delay build-up, and phase rotation
            </p>
          </div>
        </div>

        <button
          type="button"
          className="btn btn-ghost btn-sm btn-circle"
          aria-label={isOpen ? 'Collapse theory notes' : 'Expand theory notes'}
        >
          {isOpen ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
        </button>
      </div>

      {isOpen && (
        <div className="border-t border-base-200 px-5 py-4 space-y-6 text-sm text-base-content/90">
          {/* Section 1: The Significance of Phase */}
          <div>
            <div className="flex items-center gap-2 mb-2 font-semibold text-base text-accent">
              <Sparkles className="w-4 h-4" />
              <span>1. Why Phase Governs Seismic Interpretation</span>
            </div>
            <p className="leading-relaxed">
              In Section 1.1, Oz Yilmaz demonstrates that <strong>amplitude spectra alone do not define a wavelet</strong>.
              Two wavelets can possess 100% identical amplitude spectra, yet look completely different in the time domain depending on their phase spectra.
              While amplitude controls bandwidth and vertical resolution, phase governs <em>arrival timing</em>, <em>symmetry</em>, and <em>peak energy location</em>.
            </p>
          </div>

          {/* Section 2: Wavelet Phase Categories */}
          <div>
            <h3 className="font-semibold text-base text-accent mb-2">
              2. Canonical Wavelet Phase Classes
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              <div className="p-3 bg-base-200/50 rounded-lg border border-base-300 space-y-1">
                <div className="font-bold text-xs uppercase tracking-wider text-primary">Zero-Phase Wavelet</div>
                <p className="text-xs text-base-content/80 leading-relaxed">
                  Symmetric about <MathFormula math="t=0" /> with the highest peak amplitude for a given spectrum. Ideal for seismic interpretation because the central peak lines up exactly with geological interfaces. However, it is non-causal (energy arrives before <MathFormula math="t=0" />).
                </p>
              </div>

              <div className="p-3 bg-base-200/50 rounded-lg border border-base-300 space-y-1">
                <div className="font-bold text-xs uppercase tracking-wider text-success">Minimum-Phase Wavelet</div>
                <p className="text-xs text-base-content/80 leading-relaxed">
                  Strictly causal (<MathFormula math="w(t) = 0" /> for <MathFormula math="t < 0" />) with energy front-loaded closest to the onset. Physically generated by explosive dynamite charges and airguns in the field.
                </p>
              </div>

              <div className="p-3 bg-base-200/50 rounded-lg border border-base-300 space-y-1">
                <div className="font-bold text-xs uppercase tracking-wider text-secondary">Maximum-Phase Wavelet</div>
                <p className="text-xs text-base-content/80 leading-relaxed">
                  Causal time-reversal of minimum phase. Energy is back-loaded, accumulating most of its power towards the end of the wavelet duration.
                </p>
              </div>
            </div>
          </div>

          {/* Section 3: Energy Build-Up Theorem */}
          <div>
            <h3 className="font-semibold text-base text-accent mb-2">
              3. Cumulative Energy Build-Up Theorem (Yilmaz Fig 1.1-8)
            </h3>
            <p className="leading-relaxed mb-2">
              The fundamental mathematical property of a minimum-phase wavelet is its minimum energy delay. The cumulative energy is defined as:
            </p>
            <div className="p-3 bg-base-200/60 rounded-lg text-center font-mono overflow-x-auto my-2">
              <MathFormula math="E(t) = \frac{\sum_{\tau \le t} w^2(\tau)}{\sum_{\text{all } \tau} w^2(\tau)} \times 100\%" display />
            </div>
            <p className="text-xs text-base-content/80 leading-relaxed">
              For any collection of causal wavelets sharing the same amplitude spectrum, the minimum-phase curve <MathFormula math="E_{\min}(t)" /> lies above all other curves at every time step <MathFormula math="t" />.
            </p>
          </div>

          {/* Section 4: Phase Rotation via Hilbert Transform */}
          <div className="p-3 bg-base-200/60 rounded-lg border border-base-300">
            <div className="flex items-center gap-2 font-bold text-xs uppercase text-accent mb-1">
              <Compass className="w-4 h-4" />
              <span>Phase Rotation (Hilbert Transform)</span>
            </div>
            <div className="text-xs leading-relaxed space-y-1">
              <p>
                Rotating a zero-phase wavelet by an arbitrary angle <MathFormula math="\theta" /> is performed using the quadrature component via the Hilbert transform <MathFormula math="\mathcal{H}[w(t)]" />:
              </p>
              <div className="text-center py-1">
                <MathFormula math="w_\theta(t) = \cos(\theta) w(t) + \sin(\theta) \mathcal{H}[w(t)]" display />
              </div>
              <p className="text-base-content/70">
                A <MathFormula math="90^\circ" /> phase rotation transforms a symmetric peak into an antisymmetric zero-crossing doublet, distorting reservoir boundary interpretation.
              </p>
            </div>
          </div>

          {/* Reference Citation Footer */}
          <div className="pt-2 border-t border-base-200 flex items-center justify-between text-xs text-base-content/60">
            <span>Reference: Yilmaz, O. (2001). <em>Seismic Data Analysis</em>, Vol. 1, Ch. 1, pp. 34–36. Society of Exploration Geophysicists.</span>
            <span className="text-accent font-mono text-[11px]">Section 1.1</span>
          </div>
        </div>
      )}
    </div>
  )
}
